### ISSUE TITLE
Whitespaces in rt files

### ISSUE THREAD

**Issue by u413-284-si** [u413-284-si/miniRT#19]
Currently it seems that only spaces are accepted between number blocks

Whenever a tab or another kind of whitespace is present, the prog throws an error à la: 

Error
Line type not recognized
Line number [ignoring empty lines]: <0>

At least tabs should be accepted

**Comment by gwolf-011235** [comment]
Yes, right now we only check for space as delimiter. It should be fairly easy to adapt, but could also introduce bugs with some whitespace shenanigans (e.g. I don't know what a carriage return would do)

"At least tabs" -> which would be horizontal tab ('\t'). 

Since at least: Should all whitespace be allowed? All POSIX whitespaces are 
- space, 
- form-feed ('\f'), 
- newline ('\n'), 
- carriage return ('\r'), 
- horizontal tab ('\t'), and 
- vertical tab ('\v') 

To minimize potential bugs I suggest to only additionally accept horizontal tab ('\t').

**Comment by u413-284-si** [comment]
Yes, horizontal tabs are next to normal spaces the most common whitespaces. Whilst searching for different test .rt files, the majority contained either spaces or htabs. The others can be neglected.
